language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "5"
  - "6"
  - "7"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - g++-5
env:
  - SUITE=unit
  - SUITE=lint
matrix:
  exclude:
    - node_js: "0.10"
      env: SUITE=lint
    - node_js: "0.12"
      env: SUITE=lint
cache:
  apt: true
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update
  - sudo apt-get install -y gcc-5 g++-5
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 60 --slave /usr/bin/g++ g++ /usr/bin/g++-5
  - sudo update-alternatives --auto gcc
  - export CXX="g++-5" CC="gcc-5"

  # get commit message
  - COMMIT_MESSAGE=$(git show -s --format=%B $TRAVIS_COMMIT | tr -d '\n')
  # put local node-pre-gyp on PATH
  - export PATH=./node_modules/.bin/:$PATH
  # put global node-gyp on PATH
  - npm install node-gyp -g
  # install aws-sdk so it is available for publishing
  - npm install aws-sdk
  # figure out if we should publish
  - PUBLISH_BINARY=false
  # if we are building a tag then publish
  - if [[ $TRAVIS_BRANCH == `git describe --tags --always HEAD` ]]; then PUBLISH_BINARY=true; fi;
  # or if we put [publish binary] in the commit message
  - if test "${COMMIT_MESSAGE#*'[publish binary]'}" != "$COMMIT_MESSAGE"; then PUBLISH_BINARY=true; fi;
  # Not a unit tests overrides all others.
  - if [[ "$SUITE" -ne "unit" ]]; then PUBLISH_BINARY=false; fi;

install:
  - npm install --build-from-source

before_script:
  - if [[ $PUBLISH_BINARY == true ]]; then node-pre-gyp package publish; fi;
  - node-pre-gyp clean && node-gyp clean

script:
  - if [[ $PUBLISH_BINARY ]]; then npm install --fallback-to-build=false; fi;
  - npm run $SUITE

after_success:
  - if [[ $PUBLISH_BINARY == true ]]; then node-pre-gyp info; fi;
after_failure:
  - if [[ $PUBLISH_BINARY == true ]]; then node-pre-gyp unpublish; fi;
