language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "5"
  - "6"
  - "7"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - g++-5
env:
  - SUITE=unit
  - SUITE=lint
matrix:
  exclude:
    - node_js: "0.10"
      env: SUITE=lint
    - node_js: "0.12"
      env: SUITE=lint
cache:
  apt: true
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update
  - sudo apt-get install -y gcc-5 g++-5
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 60 --slave /usr/bin/g++ g++ /usr/bin/g++-5
  - sudo update-alternatives --auto gcc
  - export CXX="g++-5" CC="gcc-5"

script: npm run $SUITE
