language: node_js
node_js:
  - "0.12"
  - "4"
  - "5"
  - "6"
  - "7"

dist: trusty

env:
  - SUITE=lint
  - SUITE=unit
  - SUITE=integration
matrix:
  exclude:
    - node_js: "0.12"
      env: SUITE=lint

script:
  - npm run $SUITE
